import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 侧边栏由 docs 目录结构自动生成：
 *   docs/intro.mdx             → 活动总览（sidebars 第一项）
 *   docs/activity/_category_   → 活动说明
 *   docs/clubs/_category_      → 社团风采（入口为 docs/clubs/index.mdx）
 * 各文件夹/文档的 label 与顺序由 _category_.json 和 frontmatter 的 sidebar_position 控制。
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
